### PR TITLE
Add support for Django 1.11

### PR DESCRIPTION
**Pull request by RouganStriker**
* In Django 1.11 fields are validated during lookup

### CODE REVIEW

**Comment by sibartlett** [comment]
What you mean? Django now validates the arguments to `.get()` and `.filter()`?

**Comment by RouganStriker** [comment]
Yea, in the import-export it was throwing a validation error when it tries to look up a task by UUID with the value "T2"; it complains that "T2" is not a valid UUID so it is doing validation somewhere

**Comment by sibartlett** [comment]
Was this not needed?

**Comment by RouganStriker** [comment]
Good question...We should test this case and see if it still applies

**Comment by RouganStriker** [comment]
In our implementation we are overwriting the method so the fix was applied to our code. This is just an upstream fix for 1.11 support.

**Comment by funkaoshi** [comment]
Good job @RouganStriker. Simon should we merge it in (once the builds pass)?

**Comment by sibartlett** [comment]
Fixed in #12

**Pull request closed without merging**
